### ISSUE TITLE
Naming different sized icons

### ISSUE THREAD

**Issue by revolter** [dkhamsing/ios-asset-names#16]
What if I need multiple sizes for the same icon? I don't want to use "normal", "big", "bigger". Should I name them like `icon-20x10`?

**Comment by dkhamsing** [comment]
good question
i think designers prefer to have the size right there but that seems like a nightmare to manager

i would go with -small, -medium, -big if that makes sense
but what you have could work too

**Comment by dkhamsing** [comment]
what i mean is manage changes.. if the size change, then for sure you will either have a size mismatch or you have to change all the icons

**Comment by revolter** [comment]
The problem is when I need a new icon that's bigger than `small` but smaller than `medium` 😂

**Comment by dkhamsing** [comment]
yeah it's basically tricky when you dont have the whole picture

if you feel the size will not change over time and you are just adding sizes, then your original idea works
